services:
  feedback-service:
    image: "feedback-service"
    container_name: "feedback-service"
    depends_on:
      postgres-feedbacks:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-feedbacks:6433/feedback_service_db

  postgres-feedbacks:
    image: "postgres:16.1"
    container_name: "postgres-feedbacks"
    ports:
      - "6433:6433"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedback_service_db
      - PGPORT=6433
    volumes:
      - db-feedbacks:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-p", "6433", "-d", "feedback_service_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db-feedbacks:
    driver: local