spring.application.name=feedback-service
server.port=9093
# When the server receives a SIGTERM signal, it will stop accepting new requests
# but continue processing those already in progress for the duration specified
# in spring.lifecycle.timeout-per-shutdown-phase (default is 30 seconds).
# More details: https://habr.com/en/companies/maxilect/articles/666090/
server.shutdown=graceful
# Tomcat settings
# How long Tomcat waits after opening a connection before receiving a request.
# Useful to protect from DoS attacks where a client opens connections but sends no requests.
# This time also applies to reading the request body.
server.tomcat.connection-timeout=3s
# How long Tomcat keeps a connection open waiting for new requests.
server.tomcat.keep-alive-timeout=20s
# Maximum number of threads in the pool (one connection = one thread) 200
server.tomcat.threads.max=32
# Minimum number of threads created in the pool at startup.
server.tomcat.threads.min-spare=10
# Time during which in-progress requests can complete after receiving SIGTERM.

# DataSource Configuration
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5433/feedback_service_db
# Default connection pool size (HikariCP).
# Recommended formula: connections = ((core_count * 2) + effective_spindle_count)
# Since SSD is assumed (no spinning disks), effective_spindle_count = 0.
# Assuming 4 CPU cores => maximum-pool-size = 8
# More details: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing 12
spring.datasource.hikari.maximum-pool-size=32
# Timeout for getting a connection from the pool (in milliseconds)
spring.datasource.hikari.connection-timeout=2000
# Time during which in-progress requests can complete after receiving SIGTERM.
spring.lifecycle.timeout-per-shutdown-phase=30s

# JPA / Hibernate Configuration
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
# Format SQL queries for readability in logs
spring.jpa.properties.hibernate.format_sql=true
# Show SQL queries in logs (for debugging/testing)
spring.jpa.properties.hibernate.show_sql=false


# === Spring Cloud Config ===
spring.config.import=${configserver.import}
spring.cloud.config.import-check.enabled=false
spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.1
spring.cloud.config.label=metrics
# discovery_service # security_client # monitoring

eureka.client.service-url.defaultZone=${external.discovery-service-url}
eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=5
eureka.instance.prefer-ip-address=true

configserver.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:9095}
external.discovery-service-url=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}
external.zipkin-endpoint=http://localhost:9411/api/v2/spans
external.loki-url=http://localhost:3100/loki/api/v1/push

management.endpoints.web.exposure.include=*
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=b3
management.zipkin.tracing.endpoint=${external.zipkin-endpoint}
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.all=true
#metrics
management.metrics.enable.jvm=true
management.metrics.enable.http.server=true
management.metrics.enable.hikaricp=true
management.metrics.enable.tomcat=true

# SpringDoc / Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# API Documentation Metadata
api.feedback-create.summary=Create feedback for a course
api.feedback-create.description=Creates feedback for a course and saves it in the database. Also updates the course rating based on the user?s score. Returns information about the created feedback, including its ID. A user can only create one feedback per course.

api.feedback-get.summary=Get feedback
api.feedback-get.description=Returns information about feedback by its ID.

api.user-feedbacks-get.summary=Get list of user feedbacks
api.user-feedbacks-get.description=Returns a list of feedbacks submitted by the user. The list may be empty if the user has not created any feedback. Feedbacks are sorted by the specified sorting parameter. Available sorting options: date_asc (ascending), date_desc (descending).

api.course-feedbacks-get.summary=Get list of feedbacks for a course and its rating information
api.course-feedbacks-get.description=Returns a list of feedbacks for a specific course. The list is sorted by creation date (ascending or descending). If no feedback exists, rating and average score are 0.0. Also returns course rating calculated using Wilson Score Confidence Interval.

api.ratings-get.summary=Get information about course ratings and average scores
api.ratings-get.description=Returns ratings and average scores for courses specified in the request body. If a course has no feedback with a score, its rating and average score will be 0.0.


# API Response Messages
api.response.createOk=Feedback successfully created.
api.response.createConflict=Feedback not created because the user already submitted feedback for this course.
api.response.createBadRequest=Feedback not created because the request contains errors. See the error message for details.

api.response.getOk=Feedback successfully retrieved.
api.response.notFound=Feedback with this ID not found in the database.
api.response.getBadRequest=Unable to retrieve feedback due to invalid request parameters. See the error message for details.

api.response.getUserFeedbacksOk=User feedback list successfully retrieved.
api.response.getUserFeedbacksBadRequest=Unable to retrieve user feedback list due to validation errors. See the error message for details.

api.response.getCourseFeedbacksOk=Course feedback list successfully retrieved.
api.response.getCourseFeedbacksBadRequest=Unable to retrieve course feedback list due to validation errors. See the error message for details.

api.response.getRatingsOk=Course ratings and average scores successfully retrieved.
api.response.getRatingsBadRequest=Unable to retrieve ratings and average scores due to validation errors. See the error message for details.